### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-jad#2]
[Reporte de ENTREVISTA.pdf](https://github.com/user-attachments/files/17639064/Reporte.de.ENTREVISTA.pdf)

**Comment by IrvinSanchez-dev** [comment]
DADO A LA RUBRICA DE EVALUACIÓN OBTUVIERON UN 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
